<!DOCTYPE HTML>
<html>
	<head>
		<title>phrits.com &ndash; Leaving IT</title>

<?php include 'head.html'; ?>

	</head>

	<body class="is-preload">
<?php include 'writing_header.html'; ?>
		<!-- Wrapper -->
		<div id="wrapper">
				<!-- Main -->
			<section id="main" class="wrapper">
			<h1 class="major credits">Why I'm Leaving IT</h1>
			<span class="image fit"><img src="/images/information_technology.jpg" alt="floating icons" /></span>
            <div class="wrapper style3 inner">

            <h3>Written June, 2012</h3>

                    <p>Corporate Information Technology has been a great career for me, but I have no future in it. The jobs have evaporated. The hiring process is broken. The few jobs that are available aren't very good. And I'm tired of feeling put upon and unappreciated. It's time to move on.</p><!--more-->
                    <p>I entered the Corporate IT market right from college. My first professional job, in February 1994, was answering telephones as a support technician for a small PC software company. I knew PCs and their operating systems. I quickly learned the software. The Internet was just beginning to buzz, and right out of school,  I knew more about it than almost anyone who wasn't administering it for a living. It was a good time to be a computer geek.</p>
                    <p>In the early 1990s, our digitized future was obvious to anyone who was in a place to see where we were. We geeks starting our careers saw kindred spirits in the automotive enthusiasts of the 1920s and 30s. We talked about Turing tests and admired Bill Gates for sticking it to the big guys. We navigated directory structures and queried databases from command line interfaces: There were Apple fanboys even then, but the WIMP interface&mdash;Windows, Icons, Mice, and Pointers&mdash;had not yet become ubiquitous. We were pioneers, trailblazers, and homesteaders, ready to stake our claims in the New World.</p>
                    <p>Information Technology has been fun and the career has treated me well. For almost 25 years&mdash;counting experience before and during college&mdash;I learned new things and faced new challenges every day. The economy's technology bubble lifted my salary, more than tripling it in the first decade. And just before that bubble popped, I landed a job with a big bank. I ended up staying with the bank for longer than anywhere else I'd been. My income plateaued, but it was still clean work with good benefits. And the challenges kept coming.</p>
                    <p>We were automating everything! Along the way, I wrote programs dispatching third-party repair techs: All the help desk operator had to do was key data into a few fields on the screen, and a technician would show up to replace a hard drive or upgrade a monitor. I designed and implemented systems that let different company's Network Operations Centers work seamlessly together across miles, oceans, and timezones. I once built a company sales report that pulled information from six different sources, learning to use at least as many software tools to do so.</p>
                    <h2>There Are No Jobs.</h2>
                    <p>Today, that's the job of <i>middleware</i>, software specifically designed to allow one program to communicate with another. Middleware is good stuff! It enriches our modern lives in ways most people don't see. Middleware allows your smartphone to synchronize your Facebook contacts with your personal address book, for example, or lets you pull cash out of an ATM that isn't your bank's.</p>
                    <p>In the course of automating our industry, we have developed communications standards and protocols, best practices, and routine approaches to problems. The report that took me months to develop in the late 90s might today only require a few clicks of a mouse. The education that I needed to develop it would today be unnecessary. No one needs a Math or Computer Science degree to use a typical Windows application.</p>
                    <p>So the other thing we did by automating was put ourselves out of work. Just as yesterday's typing pool has been replaced by a word processor on every manager's laptop, many of the jobs people were doing have been replaced by software. Buying a license for QuickBooks is a lot cheaper than hiring a full time bookkeeper.</p>
                    <p>Inventory management, equipment maintenance schedules, sales reports, invoices, immunization records, expense reimbursement, etc.: No one likes paperwork, but shuffling pages used to provide jobs. Telephone operators and office receptionists have been replaced by applications that use voice recognition and synthesis. Many people now have wills, trusts, and powers-of-attorney, because software makes adequate products available cheaply and on anyone's schedule. Pharmacists' days are numbered.</p>
                    <p>For the most part, these changes have been good. Activities that used to run on a daytime weekday schedule&mdash;banking, shopping, and renewing a driver license&mdash;can now be done from nearly anywhere, any time.</p>
                    <p>And while we were automating the rest of the world, you can bet we were automating our own jobs. The intent of that six-source company sales report was to show management where sales were strong or weak, where we were getting revenue, and so on. But my own goal&mdash;encouraged all the way up the management chain&mdash;was to have the report show up in my grandboss's inbox without anyone putting it there. Automation is what what we geeks did, and I am proud to have been one of the many who did it well.</p>
                    <p>But many of us have been left with a lousy employment outlook. There will always be jobs for rock star database administrators and Unix gurus who grok the kernel in its fullness. I have usually been on the upper end of pretty good, and I've knocked off a few pairs of socks in my day. But I'm neither rock star, nor guru.</p>
                    <p>My story is common: Start on the phones, move up to testing or programming or networking. From there, many of us then shifted toward the business side of the house: Business Analysis or one of the dozens of business process management disciplines: Project or Program Management, Change, Incident, and Vendor Relationship management, and so forth.</p>
                    <p>Real, mostly necessary work. All the same work, in fact, that business people have always done. But now structured. Disciplined. Efficient. Ready for automation.</p>
                    <p>We geeks came out of our nerdy little shells and developed people skills. We polished strong verbal and written communication abilities and had team-focused, can-do attitudes. We built current-state process models and gathered testable requirements from end users who had been doing their jobs so long they didn't even know what they actually did. We attended and facilitated countless, endless, pointless meetings.</p>
                    <p>And our specialized skills obsolesced right along with the software platforms on which we'd learned them. The tech skills we'd had were continually leapfrogged by new, better ways coming out of the colleges and off the Internet. So we moved along on our upward career paths&mdash;as our peers and parents in other careers always had&mdash;still doing our best jobs, still working too many hours, but leaving the low-level coding work to the low-level workers.</p>
                    <p>Many of those low-level programming jobs are now overseas, mostly in India and China. Working across timezones and language barriers is even more difficult than it sounds, so more and more of the mid-level roles have begun to follow. That trend will continue. Until software catches up, anyway.</p>
                    <h2>If There Is a Job, I Won't Be Able to Find It.</h2>
                    <p>To look at the job boards, it would seem that there are a lot of IT jobs out there. And really, there are a lot of spots to fill. But hiring managers can't find folks for the jobs. Money is only part of the problem. The real barrier to finding work is modern IT hiring practices.</p>
                    <p>The big companies have largely automated their hiring, which means that they can drill down through a stack of r&eacute;sum&eacute;s to find the perfect candidate for a job they're trying to fill. They often use a particular set of preferred vendors, so their hiring managers don't spend their days harassed by cold calls from placement firms. Job seekers can post their r&eacute;sum&eacute;s and profiles, with hopes to be picked up for their dream jobs. It sounds like a win for everyone involved.</p>
                    <p>The problem lies in the fact that what the industry refers to as <i>human resources</i> are actually <i>human beings</i>. The hiring managers, too. And recruiters. And maybe even some of the folks who work in corporate Human Resources (HR) departments. The systems and processes used, on the other hand, are completely dehumanizing, possibly even by design.</p>
                    <p>To find an IT job, a candidate submits their r&eacute;sum&eacute; to Monster, Dice, and any of thousands of other placement sites. Corporations usually link to jobs or careers from their websites, but they're typically poorly implemented decoys. If the jobs are even real, there's usually an internal candidate for whom the role was created.</p>
                    <p>A good r&eacute;sum&eacute; is a well-formatted, well-written summary of the candidate's abilities and experience. It's a snapshot of professional a life and is supposed to give some sense of what the candidate has done, who they are, where they're going, what sorts of things they're good at. All useful information for hiring managers.</p>
                    <p>Advice on writing r&eacute;sum&eacute;s encourages job seekers to highlight accomplishments, rather than responsibilities they've had. Those nights we carried a pager instead of doing something fun and all those meetings we called into from vacation count for nothing. We're told to list dollars we've saved for our previous employers, or to otherwise declare numbers. We're told to present action verbs and bullet points.</p>
                    <p>Horsefeathers.</p>
                    <p>An IT job candidate's r&eacute;sum&eacute; is neither more nor less than the keywords that can be extracted and put into the recruiter's job-matching application. Systems are talking to systems at that stage; no humans are involved. Spelling counts&mdash;keywords are fairly exact&mdash;but the rest of it is just noise. If presentation does matter, the recruiter will tell you what to change. And maybe where to add some experience while you're at it.</p>
                    <p>The old adage &ldquo;it's who you know&rdquo; doesn't hold water anymore, either. Even if you know the hiring manager. Even if he made a point of telling you he was hiring. Even if he knows you're a great fit for the position. Even if you have years of shared working experience. If you don't have the specialized detail on your r&eacute;sum&eacute; to check the box the hiring manager is required to fill, you're not getting the job. You probably won't even get the interview.</p>
                    <p>In most cases, job applications and r&eacute;sum&eacute;s might as well be dropped into a black hole. If your r&eacute;sum&eacute; matches a lot of the keywords sought, a recruiter will call to get more information. But unless your specialized skills happen to match the specific position they're trying to fill, that is the last time you will hear from that recruiter. Ever. Or maybe they'll call in a few weeks or months when another close match comes up. It's a toss-up as to whether they'll remember having talked to you before.</p>
                    <p>So finding a good job is a crap shoot. In my particular case, it's a crap shoot with dice loaded against me. My &ldquo;specialized&rdquo; skills include obsolete versions of powerful applications, databases, and operating systems, a great number of home-grown applications, and an unsurpassed ability to wield an email.</p>
                    <p>It doesn't matter that I have made a career of understanding software. It doesn't matter that the modern versions of the systems I knew have not changed much: The keyword filter includes a version number I can't honestly pass. No one has heard of the custom applications. And just try putting a number to being able to send a bridge-building electronic message.</p>
                    <p>I do not believe my situation is unique.</p>
                    <p>The keyword approach does work in a very few particular cases. For example, if you happen to have a specialized skill being sought, and if your r&eacute;sum&eacute; happens to be in the recruiter's stack when he's looking for it, and you happen to be at a break between contracts&mdash;<i>drawing unemployment</i>, if you will&mdash;and if you're able to accept 70% of what the same job paid in 2006, you have a shot at a phone screening, and from there maybe an interview.</p>
                    <p>There are a few generalist jobs out there, too. But there are also a lot of other people equally or better qualified. No matter who you are. I've sent in r&eacute;sum&eacute;s. When the stakes are high enough, I also buy lottery tickets.</p>
                    <p>There is another way to get in. There are a few good recruiters out there, who really will work to find someone a job. I know because I had the great pleasure of working with one. But they're rare. I understand if you don't believe I've met one. I have never recruited, but I have come to loathe IT recruiters the way one might loathe a trailer park landlord, a grouchy cop, or a Chief Technology Officer.</p>
                    <p>But to be fair, recruiters are incited to place anyone anywhere. Their jobs ask them to fill higher positions for lower wages. To have a large candidate pool and to make a lot of phone calls. Taking the time to find a good manager-employee match is money out of their pocket. And usually pointless. Many recruiters have begun to automate the outreach messages, the teasers that keep a candidate's attention. I wonder if they think of John Henry.</p>
                    <p>After the phone screening, you might get an interview with a panel or even the hiring manager. And from there, a job. Sort of, anyway. It's probably a contract position.</p>
                    <h2>If I Can Find a Job, It Won't Be Very Good for Anyone.</h2>
                    <p>A job is a job, and contractors and employees both get paid. Employees get a week or three of vacation; maybe some sick time, family time, volunteer time, bereavement leave, and paid holidays; medical, dental, and vision benefits; and the general ability to plan weddings, graduations, and holidays more than a year into their futures.</p>
                    <p>Contractors get a mandatory day off, and a 20% pay cut for each week with a federal or state holiday. They get no vacation, no sick time, no bereavement leave, and no easy give-and-take over work hours. They do get the assurance that if the budget gets tight, they'll be the first ones on the street without notice.</p>
                    <p>Most large companies have caps on how long a contractor can work before being dismissed. Microsoft found out a few years back that <i>de facto</i> employees do have a few rights, and corporations have since been careful to make the distinction clear.</p>
                    <p>As a contractor, you're a temporary worker, and it's unlikely your boss or even grandboss has the power to change that. No matter how hard you work, how dedicated to the team you are, how many long-standing problems you solve. It doesn't matter if you've become the boss's right hand: If you're capped at 18 months, you're gone at 18 months.</p>
                    <p>Which doesn't mean you can't come back. But you'll have to wait until the company's waiting period between contracts has expired. And you'll make a little less than last time you were there.</p>
                    <p>Managing a staff of contractors seems to be less work than managing full time employees. There are no performance reviews to worry about or goals to track. Troublemakers and slackers are gone with a phone call. There's less company propaganda <i>&agrave; la</i> training to track. There are fewer coverage schedules to juggle.</p>
                    <p>But managers lose more than they gain. Contractors have no real stake in their teams' successes, so they only have to do mediocre or poor jobs. As long as it's cheaper and less work to keep them than replace them, the job will usually last the contract. Of course, there is no unpaid overtime out of a worker who has come to resent Labor Day for the wage it costs.</p>
                    <p>The idea that it's less work to manage contractors is a false gain. A good manager used to be able to build a solid team they could grow with and keep for years. Along the way, they could delegate administrivia&mdash;invoices and on-call schedules; executive reports and network access requests&mdash;but what's left of the core team is overloaded with their bread-and-butter work. The manager has to take the work so it gets done, and then it's easier to do it at night than to find time to train a contractor during the day.</p>
                    <p>Along with building such a team, a good manager ended up with a group that could do anything, pull off any job. Each team had its own lore, its own heroes, villains, and unaligned outlaws. We knew who'd pull through in the crunch, and who was going to need a hand with the overload. We could be a whole, greater than the sum of our parts. Friends and co-combatants, us and them, brothers and sisters in arms, and brother vs. brother: The digerati, bringing fire to the unteched masses.</p>
                    <p>But our teams are all but gone, the remaining few hidden, huddled together against the cold. The vets remaining have no time for that extra cup of coffee with the fellow from the next cube. There's no point in trying to make friends with a contractor, even if you are one. They might be gone tomorrow. And surely long before you'd expect them to show up at your young son's birthday party.</p>
                    <h2>If I Can Find a Good IT Job, I Don't Really Want It Anymore.</h2>
                    <p>My technical background is in communications, maintenance, and the applications that support them. My mid-career business experience has been in supporting the software development life cycle, disciplines related to risk mitigation, and communications. There was a time when I was a true believer. I mostly still am. But I've lost my zeal. I am no longer goaded by windmills.</p>
                    <p>I still believe that good software starts with good requirements. I understand that it's mathematically impossible to squash all the bugs, but that we have to test and kill what we can: The earlier a problem is detected, the cheaper is it to fix. I know there is immeasurable value in careful planning before implementing changes into production systems. It is an article of faith with me that a software tool can never be better than the business process it supports. But I've lost my interest in spreading the word.</p>
                    <p>And for all the good we've done, all the problems we've solved, all the redundancies and filing cabinets we've eliminated, working in IT has always been a thankless job. Infrastructure costs money. Whether it's water to flush your toilets or the network that allows you to track your global sales in real time, doing business costs money. Cost is always the enemy, and cost centers&mdash;the plumbing department or the network operations center&mdash;are full of costs. So when your top sales dude demands a new laptop, you buy it. But when the support printer is out of paper, you tell them to print less.</p>
                    <p>All the noise about geeks becoming cool and accepted is more sound than fury. It's human nature to undervalue something you don't understand. My personal, mild contempt for salespeople and marketeers is mirrored&mdash;and is surely as justified&mdash;as their frequent assumption that I need only push a few buttons to solve any problem. Ignorance abounds!</p>
                    <p>It's just as well that I'm ready to move on. As the economy recovers, if it recovers, most of the jobs will come back. Houses will sell again, so construction workers and home inspectors and property managers will have jobs. Restaurants will be full, so waiters and cooks and <i>sommeliers</i> will again wait, cook and push pretentious wine. Department store chains will need cashiers and store managers and corporate accountants. But IT isn't coming back.</p>
                    <p>There's really no long term future in Information Technology. We've automated what we can, and we'll automate what we haven't, faster and faster, more and more efficiently.</p>
                    <p>Even people are being automated. When I started on the phones, callers heard hold music until a technician answered the phone. The tech answered with name and company&mdash;proper telephone etiquette&mdash;and listened to the caller. We asked questions and used our best judgments to troubleshoot and solve problems. We developed relationships that often kept those customers from going elsewhere. But it's not like that anymore.</p>
                    <p>If you call a help line today, you might eventually reach a human being. Sort of. That person is working from a script, usually with no other choice. Calls are recorded and monitored, and deviations from the script are <i>verboten</i>.</p>
                    <p>It's menial work for lousy pay and less appreciation. If you're in support, you're listening to angry people all day. If you're in sales, you're pissing people off with cold calls. You have no power to solve any but the most basic problems. Your every working minute is monitored&mdash;you may void your bladder only when scheduled&mdash;and your favorite available reward for a job well done is to be allowed to wear blue jeans to work an extra day one week.</p>
                    <p>Customers prefer to speak to people. People are expensive. So we find the cheapest warm bodies we can find, and we automate them. Human resources. At least until the technology catches up.</p>
                    <h2>They Lied. The Grass Is Greener Over Here.</h2>
                    <p>Particularly with the current state of the economy, there has been a lot of attention paid to jobs and unemployment. I think the focus is misdirected. As technology advances, we will continue to produce more value with fewer people: The economic concept, <i>efficiency</i>.</p>
                    <p>So at some point, maybe not too far off, there will simply not be enough work to go around. We're going to have to rethink some things, and we're going to have to refigure what it means to be a contributing member of society. How can we require a hungry person to work for food if there is no job to do? </p>
                    <p>When I found myself unemployed, I learned to get by on less. When the unemployment system hiccuped and I had no income, I learned the lesson better. And I had time to notice that there's a world outside the cubicle. There are people doing other things.</p>
                    <p>There are folks working for themselves, building human relationships with customers and employees, buying, selling, hiring. People working with people. That's hard-wired. Therein lies a future. My IT career is winding down to its end, but I learned a lot from it. Much of what I learned, I expect to use again, later if not sooner.</p>
                    <p>As it happens, I have a great passion for food and cooking. While living a more-or-less average white-collar life, I've had the time and the resources to learn and practice my hobby. I know a good bit. I have more to learn than I can yet grasp. But when my current contract ends, I'll begin my cooking career.</p>
                    <p>Cooking is personal, even if you don't see the person you're feeding. Food is one of the few, universal human constants: A unifying element in every known human society and culture. And we've begun to notice&mdash;maybe just in time&mdash;that food is more than just its nutrients. We're starting to shift back toward where we came from, but we're swapping recipes all over the globe while we do it.</p>
                    <p>There's a buzz beginning to demand real food. I know more about it than almost anyone who isn't already in the profession. It's a good time to be a food geek.</p>
                    <p>I know I'm facing some big changes. I'll be back at the bottom. There are unknowns both known and unknown. There will be challenges. And problems to solve. Yep. Time to jump.</p>
                    <p>It worked the last time.</p>
                    <br /><hr />
                    <i>
                    <p>Originally published at <a href="http://analytical-life.com">Analytical Life</a> on 2012-06-03.</p>
                    </i>

            <div class="wrapper style3 inner">


            </div> <!-- class="wrapper style3 inner" -->
			</section>
	</div> <!-- wrapper -->

<?php include 'footer.html'; ?>

<?php include 'scripts.html'; ?>

	</body>
</html>