# Generated by Django 4.0 on 2021-12-29 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phrits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_modify_by', models.CharField(max_length=255)),
                ('txt_content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('phrits_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Scrape.phrits')),
                ('url', models.URLField()),
                ('url_text', models.CharField(default='link text', max_length=255)),
            ],
            bases=('Scrape.phrits',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('phrits_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Scrape.phrits')),
                ('int_sequence', models.IntegerField(default=-1)),
                ('s_title', models.CharField(default='Title', max_length=255)),
            ],
            bases=('Scrape.phrits',),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Scrape.section')),
            ],
            bases=('Scrape.section',),
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Scrape.section')),
            ],
            bases=('Scrape.section',),
        ),
        migrations.CreateModel(
            name='Rec_Ingredient',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Scrape.section')),
                ('quantity', models.CharField(default='quantity', max_length=64)),
                ('measure', models.CharField(default='measure', max_length=64)),
                ('ingredient', models.CharField(default='ingredient', max_length=64)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('raw', models.BooleanField(default=False)),
                ('fat_free', models.BooleanField(default=False)),
                ('embellishment', models.TextField()),
            ],
            bases=('Scrape.section',),
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('paragraph_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Scrape.paragraph')),
            ],
            bases=('Scrape.paragraph',),
        ),
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('paragraph_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Scrape.paragraph')),
            ],
            bases=('Scrape.paragraph',),
        ),
        migrations.CreateModel(
            name='Rec_IngredientList',
            fields=[
                ('itemlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Scrape.itemlist')),
            ],
            bases=('Scrape.itemlist',),
        ),
    ]
